### ISSUE TITLE
Doesn't work with Trans component

### ISSUE THREAD

**Issue by PeterKottas** [i18next/i18next-emoji-postprocessor#1]
## 🐛 Bug Report

This doesn't work with Trans component.

## To Reproduce

Just use any trans component, it won't work.

## Expected behavior

It should work.

## Your Environment

Irrelevant here, this is likely a missing feature for now.

**Comment by PeterKottas** [comment]
Just to clarify, this is how I am using the trans component:
```
<Trans i18nKey="key">
  Special{' '}
  <span className="font-weight-light">
    (e.g. bank holidays, events ...)
  </span>
</Trans>
```
where the translation would be:
```
{
  ...,
  key: 'Special <2>(e.g. bank holidays, events ...)</2>',
  ...
}
```

**Comment by adrai** [comment]
Can you try to add the `postProcess: 'emoji'` option?

I suspect postProcess is not the working without that option for Trans component...
Need to ask @jamuhl if he knows more... I also suspect the tOption for Trans component is completely ignored...

This is probably because the overloadTranslationOptionHandler option is only executed, if no t options are passed...

This change in Translator.js fixes it, but breaks an older compatibility test:
![image](https://user-images.githubusercontent.com/1086194/83348784-ec366680-a32f-11ea-9c64-af88ff17cdc2.png)

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L259 you can pass in options via prop `tOptions`

**Comment by adrai** [comment]
Yes, setting tOptions individually works:
![image](https://user-images.githubusercontent.com/1086194/83351167-e9dd0800-a341-11ea-838c-9cc3e56e167c.png)

**Comment by PeterKottas** [comment]
Thanks  guys, I can confirm that adding:
```
postProcess: 'emoji'
```
to i18next options fixes this issue. Apparently there is no need to add this for every Trans component when that option is provided.

**Comment by adrai** [comment]
@PeterKottas Yes, that works, but it’s not an official api option... I’ve added a PR to react-i18next for further investigation next week...

**Comment by jamuhl** [comment]
@adrai it is official API -> it defines which postprocessors to run in each case: https://www.i18next.com/overview/configuration-options#translation-defaults

**Comment by adrai** [comment]
All ok, updated the readme

**Comment by PeterKottas** [comment]
Lovely, thanks for your help gents!
